### PR TITLE
Remove usage of react-loadable

### PR DESCRIPTION
**Pull request by kfarnung**
The `react-loadable` package is generating warnings when building due to
usage of deprecated APIs. There are other alternative packages, but most
of the functionality is built directly into React.

Implement using `React.lazy`, `Suspense`, and `ErrorBoundary` which are
built-in concepts. To avoid a boilerplate `ErrorBoundary`
implementation, the `react-error-boundary` package is used. In the event
that becomes an issue, the implementation is pretty simple.

### CODE REVIEW

**Comment by kfarnung** [comment]
Looks like there's a bug where the `React.lazy` is only evaluated once, even on failure.

**Comment by sjenks** [comment]
Still relevant?

**Comment by kfarnung** [comment]
The big issue is handling load failure, like when you’re offline and then go online. I’ll have to see what the status of react-loadable is these days, it seemed like it was not actively maintained and was still using deprecated features.

I’ll mark it as draft for now.

**Comment by kfarnung** [comment]
@beckbria @sjenks I think I've resolved the issues I ran into before. There's a chance that more work is done on each navigation, but I haven't seen any obvious indication yet.

**Pull request merged**
