### PR TITLE
Upgrade NPM packages

### PR DESCRIPTION
**Pull request by kfarnung**

### CODE REVIEW

**Comment by beckbria** [comment]
The Travis error is:

TypeScript error in /home/travis/build/puzztool/puzztool/src/Common/KeyedCipherStream/index.tsx(81,13):
Type '(event: FormEvent<HTMLInputElement>) => void' is not assignable to type '(event: ChangeEvent<FormControlElement>) => void'.
  Types of parameters 'event' and 'event' are incompatible.

If a minor version bump of a dependency broke this, that seems like a problem with that dependency.  Is this a pre-existing failure?

**Comment by kfarnung** [comment]
> The Travis error is:
> 
> TypeScript error in /home/travis/build/puzztool/puzztool/src/Common/KeyedCipherStream/index.tsx(81,13):
> Type '(event: FormEvent) => void' is not assignable to type '(event: ChangeEvent) => void'.
> Types of parameters 'event' and 'event' are incompatible.
> 
> If a minor version bump of a dependency broke this, that seems like a problem with that dependency. Is this a pre-existing failure?

I suspect that they don't consider typing changes to be semver. Not ideal, but not a huge deal either.

https://github.com/react-bootstrap/react-bootstrap/pull/5067

**Comment by beckbria** [comment]
Confirmed that this happens in a clean client, so this being out of date wasn't the source of the break.  Thanks for fixing - I would argue that type changes should be semver, but then again I spend most of my life in statically-typed languages.

**Comment by kfarnung** [comment]
I agree with the sentiment, but I'm just glad to see more packages maintaining their own typings rather than relying on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Pull request merged**
